fixtures:
  # use the forge modules so we can easily pin to a specific version
#  forge_modules:
#    stdlib: "puppetlabs/stdlib"
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    pam: "git://github.com/herlo/puppet-module-pam.git"
    users: "git://github.com/mthibaut/puppet-users.git"
    nsswitch: "git://github.com/herlo/puppet-module-nsswitch.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
  symlinks:
    totpcgi: "#{source_dir}"
